export const GET_RANDOM_NUMBER = "GET_RANDOM_NUMBER";
export const GET_RANDOM_NUMBER_LOADING = "GET_RANDOM_NUMBER_LOADING";
export const GET_ERROR = "GET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const RESET_RANDOM_NUMBER = "RESET_RANDOM_NUMBER";
